/* eslint-disable prettier/prettier */
export const CURRENT_GAME_INCREMENT_HOME = 'CURRENT_GAME_INCREMENT_HOME';
export const CURRENT_GAME_DECREMENT_HOME = 'CURRENT_GAME_DECREMENT_HOME';
export const CURRENT_GAME_INCREMENT_VISITOR = 'CURRENT_GAME_INCREMENT_VISITOR';
export const CURRENT_GAME_DECREMENT_VISITOR = 'CURRENT_GAME_DECREMENT_VISITOR';
export const SET_HOME_TEAM_SCORE = 'SET_HOME_TEAM_SCORE';
export const SET_VISITOR_TEAM_SCORE = 'SET_VISITOR_TEAM_SCORE';
export const SET_CURRENT_GAME_SCORE_FROM_WATCH = 'SET_CURRENT_GAME_SCORE_FROM_WATCH';
