export const COMPLETE_SET = 'COMPLETE_SET';
export const INCREMENT_HOME_TEAM_SET = 'INCREMENT_HOME_TEAM_SET';
export const INCREMENT_VISITOR_TEAM_SET = 'INCREMENT_VISITOR_TEAM_SET';
export const DECREASE_SPECIFIC_SET_FOR_HOME_TEAM_COMPLETE =
  'DECREASE_SPECIFIC_SET_FOR_HOME_TEAM_COMPLETE';
export const DECREASE_SPECIFIC_SET_FOR_HOME_TEAM =
  'DECREASE_SPECIFIC_SET_FOR_HOME_TEAM';
export const INCREASE_SPECIFIC_SET_FOR_HOME_TEAM =
  'INCREASE_SPECIFIC_SET_FOR_HOME_TEAM';
export const INCREASE_SPECIFIC_SET_FOR_HOME_TEAM_COMPLETE =
  'INCREASE_SPECIFIC_SET_FOR_HOME_TEAM_COMPLETE';
export const INCREASE_SPECIFIC_SET_FOR_VISITOR_TEAM =
  'INCREASE_SPECIFIC_SET_FOR_VISITOR_TEAM';
export const INCREASE_SPECIFIC_SET_FOR_VISITOR_TEAM_COMPLETE =
  'INCREASE_SPECIFIC_SET_FOR_VISITOR_TEAM_COMPLETE';
export const DECREASE_SPECIFIC_SET_FOR_VISITOR_TEAM =
  'DECREASE_SPECIFIC_SET_FOR_VISITOR_TEAM';
export const DECREASE_SPECIFIC_SET_FOR_VISITOR_TEAM_COMPLETE =
  'DECREASE_SPECIFIC_SET_FOR_VISITOR_TEAM_COMPLETE';
export const FIX_SET_COUNT_FROM_WATCH = 'FIX_SET_COUNT_FROM_WATCH';
