export const INCREMENT_HOME_TEAM_GAME = 'INCREMENT_HOME_TEAM_GAME';
export const INCREMENT_VISITOR_TEAM_GAME = 'INCREMENT_VISITOR_TEAM_GAME';
export const DECREMENT_HOME_TEAM_GAME = 'DECREMENT_HOME_TEAM_GAME';
export const DECREMENT_VISITOR_TEAM_GAME = 'DECREMENT_VISITOR_TEAM_GAME';
export const RESET_GAMES = 'RESET_GAMES';
